name: number_trivia_with_clean_architecture_and_tdd
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  flutter_bloc: ^7.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  connectivity: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.1.0
  data_connection_checker_nulls: ^0.0.2
  bloc: ^7.0.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # mockito: ^5.4.3
  mocktail: ^0.2.0
  bloc_test: ^8.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
